/**
 * generated by Xtext 2.32.0
 */
package geodes.sms.relis.formatting2;

import Relis.RelisRoot;
import Relis.Statistic;
import Relis.Variable;
import com.google.inject.Inject;
import geodes.sms.relis.services.RelisTextualGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class RelisTextualFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private RelisTextualGrammarAccess _relisTextualGrammarAccess;

  protected void _format(final RelisRoot relisRoot, @Extension final IFormattableDocument document) {
    EList<Variable> _variable = relisRoot.getVariable();
    for (final Variable variable : _variable) {
      document.<Variable>format(variable);
    }
  }

  protected void _format(final Variable variable, @Extension final IFormattableDocument document) {
    EList<Statistic> _statistic = variable.getStatistic();
    for (final Statistic statistic : _statistic) {
      document.<Statistic>format(statistic);
    }
  }

  public void format(final Object relisRoot, final IFormattableDocument document) {
    if (relisRoot instanceof XtextResource) {
      _format((XtextResource)relisRoot, document);
      return;
    } else if (relisRoot instanceof RelisRoot) {
      _format((RelisRoot)relisRoot, document);
      return;
    } else if (relisRoot instanceof Variable) {
      _format((Variable)relisRoot, document);
      return;
    } else if (relisRoot instanceof EObject) {
      _format((EObject)relisRoot, document);
      return;
    } else if (relisRoot == null) {
      _format((Void)null, document);
      return;
    } else if (relisRoot != null) {
      _format(relisRoot, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(relisRoot, document).toString());
    }
  }
}
