/*
 * generated by Xtext 2.32.0
 */
package geodes.sms.relis;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RelisTextualRuntimeModule extends AbstractRelisTextualRuntimeModule {
}
