/*
 * generated by Xtext 2.32.0
 */
package geodes.sms.relis;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RelisTextualStandaloneSetup extends RelisTextualStandaloneSetupGenerated {

	public static void doSetup() {
		new RelisTextualStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
