<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Relis" nsURI="geodes.sms.relis" nsPrefix="rl">
  <eClassifiers xsi:type="ecore:EClass" name="RelisRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statistic" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Descriptive" eSuperTypes="#//Statistic"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comparative" eSuperTypes="#//Statistic"/>
  <eClassifiers xsi:type="ecore:EClass" name="Evolution" eSuperTypes="#//Statistic"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="Continuous"/>
    <eLiterals name="Nominal" value="1"/>
    <eLiterals name="Comparative" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statistic" upperBound="-1"
        eType="#//Statistic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
</ecore:EPackage>
