/*
 * generated by Xtext 2.32.0
 */
package geodes.sms.relis.parser.antlr;

import com.google.inject.Inject;
import geodes.sms.relis.parser.antlr.internal.InternalRelisTextualParser;
import geodes.sms.relis.services.RelisTextualGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RelisTextualParser extends AbstractAntlrParser {

	@Inject
	private RelisTextualGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRelisTextualParser createParser(XtextTokenStream stream) {
		return new InternalRelisTextualParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RelisRoot";
	}

	public RelisTextualGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RelisTextualGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
