/*
 * generated by Xtext 2.32.0
 */
package geodes.sms.relis.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RelisTextualAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("geodes/sms/relis/parser/antlr/internal/InternalRelisTextual.tokens");
	}
}
