<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Rsc" nsURI="geodes.sms.rsc" nsPrefix="rsc">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statistic" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnDataType" eType="#//ReturnDataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Descriptive" eSuperTypes="#//Statistic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statistics" upperBound="-1"
        eType="#//DescStats"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparative" eSuperTypes="#//Statistic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statistics" upperBound="-1"
        eType="#//CompStats" defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Evolution" eSuperTypes="#//Statistic">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="statistics" upperBound="-1"
        eType="#//EvoStats"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="Continuous"/>
    <eLiterals name="Nominal" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statistics" upperBound="-1"
        eType="#//Statistic" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" ordered="false"
        unique="false" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiple" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompStats">
    <eLiterals name="FrequencyTables"/>
    <eLiterals name="StackedBarPlots" value="1"/>
    <eLiterals name="GroupedBarPlots" value="2"/>
    <eLiterals name="BubbleCharts" value="3"/>
    <eLiterals name="ChiSquaredTest" value="4"/>
    <eLiterals name="ShapiroWilkCorrelationTest" value="5"/>
    <eLiterals name="PearsonCorrelationTest" value="6"/>
    <eLiterals name="SpearmanCorrelationTest" value="7"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EvoStats">
    <eLiterals name="FrequencyTables"/>
    <eLiterals name="EvolutionPlots" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DescStats">
    <eLiterals name="FrequencyTables"/>
    <eLiterals name="BarPlots" value="1"/>
    <eLiterals name="Statistics" value="2"/>
    <eLiterals name="BoxPlots" value="3"/>
    <eLiterals name="ViolinPlots" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReturnDataType">
    <eLiterals name="Figure"/>
    <eLiterals name="DataFrame"/>
  </eClassifiers>
</ecore:EPackage>
