/*
 * generated by Xtext 2.32.0
 */
package geodes.sms.relis.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRelisTextualScopeProvider extends DelegatingScopeProvider {
}
