/*
 * generated by Xtext 2.32.0
 */
package geodes.sms.relis.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class RelisTextualGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class RelisRootElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.relis.RelisTextual.RelisRoot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRelisRootAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRelisRootKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cVariableKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cVariableAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cVariableVariableParserRuleCall_4_2_0 = (RuleCall)cVariableAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cVariableAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cVariableVariableParserRuleCall_4_3_1_0 = (RuleCall)cVariableAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//RelisRoot returns RelisRoot:
		//    {RelisRoot}
		//    'RelisRoot'
		//    name=EString
		//    '{'
		//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{RelisRoot}
		//'RelisRoot'
		//name=EString
		//'{'
		//    ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{RelisRoot}
		public Action getRelisRootAction_0() { return cRelisRootAction_0; }
		
		//'RelisRoot'
		public Keyword getRelisRootKeyword_1() { return cRelisRootKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'variable'
		public Keyword getVariableKeyword_4_0() { return cVariableKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_4_2() { return cVariableAssignment_4_2; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_4_2_0() { return cVariableVariableParserRuleCall_4_2_0; }
		
		//( "," variable+=Variable)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//variable+=Variable
		public Assignment getVariableAssignment_4_3_1() { return cVariableAssignment_4_3_1; }
		
		//Variable
		public RuleCall getVariableVariableParserRuleCall_4_3_1_0() { return cVariableVariableParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class StatisticElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.relis.RelisTextual.Statistic");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDescriptiveParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cComparativeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cEvolutionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Statistic returns Statistic:
		//    Descriptive | Comparative | Evolution;
		@Override public ParserRule getRule() { return rule; }
		
		//Descriptive | Comparative | Evolution
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Descriptive
		public RuleCall getDescriptiveParserRuleCall_0() { return cDescriptiveParserRuleCall_0; }
		
		//Comparative
		public RuleCall getComparativeParserRuleCall_1() { return cComparativeParserRuleCall_1; }
		
		//Evolution
		public RuleCall getEvolutionParserRuleCall_2() { return cEvolutionParserRuleCall_2; }
	}
	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.relis.RelisTextual.Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cVariableKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStatisticKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cStatisticAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cStatisticStatisticParserRuleCall_4_2_0 = (RuleCall)cStatisticAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cStatisticAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cStatisticStatisticParserRuleCall_4_3_1_0 = (RuleCall)cStatisticAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Variable returns Variable:
		//    {Variable}
		//    'Variable'
		//    name=EString
		//    '{'
		//        ('statistic' '{' statistic+=Statistic ( "," statistic+=Statistic)* '}' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Variable}
		//'Variable'
		//name=EString
		//'{'
		//    ('statistic' '{' statistic+=Statistic ( "," statistic+=Statistic)* '}' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Variable}
		public Action getVariableAction_0() { return cVariableAction_0; }
		
		//'Variable'
		public Keyword getVariableKeyword_1() { return cVariableKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('statistic' '{' statistic+=Statistic ( "," statistic+=Statistic)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'statistic'
		public Keyword getStatisticKeyword_4_0() { return cStatisticKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//statistic+=Statistic
		public Assignment getStatisticAssignment_4_2() { return cStatisticAssignment_4_2; }
		
		//Statistic
		public RuleCall getStatisticStatisticParserRuleCall_4_2_0() { return cStatisticStatisticParserRuleCall_4_2_0; }
		
		//( "," statistic+=Statistic)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//statistic+=Statistic
		public Assignment getStatisticAssignment_4_3_1() { return cStatisticAssignment_4_3_1; }
		
		//Statistic
		public RuleCall getStatisticStatisticParserRuleCall_4_3_1_0() { return cStatisticStatisticParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.relis.RelisTextual.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class DescriptiveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.relis.RelisTextual.Descriptive");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cDescriptiveAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cDescriptiveKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeTypeEnumRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Descriptive returns Descriptive:
		//    {Descriptive}
		//    'Descriptive'
		//    name=EString
		//    '{'
		//        ('type' type=Type)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Descriptive}
		//'Descriptive'
		//name=EString
		//'{'
		//    ('type' type=Type)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Descriptive}
		public Action getDescriptiveAction_0() { return cDescriptiveAction_0; }
		
		//'Descriptive'
		public Keyword getDescriptiveKeyword_1() { return cDescriptiveKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=Type)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=Type
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//Type
		public RuleCall getTypeTypeEnumRuleCall_4_1_0() { return cTypeTypeEnumRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ComparativeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.relis.RelisTextual.Comparative");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cComparativeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cComparativeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeTypeEnumRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Comparative returns Comparative:
		//    {Comparative}
		//    'Comparative'
		//    name=EString
		//    '{'
		//        ('type' type=Type)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Comparative}
		//'Comparative'
		//name=EString
		//'{'
		//    ('type' type=Type)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Comparative}
		public Action getComparativeAction_0() { return cComparativeAction_0; }
		
		//'Comparative'
		public Keyword getComparativeKeyword_1() { return cComparativeKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=Type)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=Type
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//Type
		public RuleCall getTypeTypeEnumRuleCall_4_1_0() { return cTypeTypeEnumRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EvolutionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.relis.RelisTextual.Evolution");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEvolutionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEvolutionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cTypeKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTypeAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTypeTypeEnumRuleCall_4_1_0 = (RuleCall)cTypeAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Evolution returns Evolution:
		//    {Evolution}
		//    'Evolution'
		//    name=EString
		//    '{'
		//        ('type' type=Type)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Evolution}
		//'Evolution'
		//name=EString
		//'{'
		//    ('type' type=Type)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//{Evolution}
		public Action getEvolutionAction_0() { return cEvolutionAction_0; }
		
		//'Evolution'
		public Keyword getEvolutionKeyword_1() { return cEvolutionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('type' type=Type)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'type'
		public Keyword getTypeKeyword_4_0() { return cTypeKeyword_4_0; }
		
		//type=Type
		public Assignment getTypeAssignment_4_1() { return cTypeAssignment_4_1; }
		
		//Type
		public RuleCall getTypeTypeEnumRuleCall_4_1_0() { return cTypeTypeEnumRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	
	public class TypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "geodes.sms.relis.RelisTextual.Type");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cContinuousEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cContinuousContinuousKeyword_0_0 = (Keyword)cContinuousEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cNominalEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cNominalNominalKeyword_1_0 = (Keyword)cNominalEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cComparativeEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cComparativeComparativeKeyword_2_0 = (Keyword)cComparativeEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Type returns Type:
		//                Continuous = 'Continuous' | Nominal = 'Nominal' | Comparative = 'Comparative';
		public EnumRule getRule() { return rule; }
		
		//Continuous = 'Continuous' | Nominal = 'Nominal' | Comparative = 'Comparative'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Continuous = 'Continuous'
		public EnumLiteralDeclaration getContinuousEnumLiteralDeclaration_0() { return cContinuousEnumLiteralDeclaration_0; }
		
		//'Continuous'
		public Keyword getContinuousContinuousKeyword_0_0() { return cContinuousContinuousKeyword_0_0; }
		
		//Nominal = 'Nominal'
		public EnumLiteralDeclaration getNominalEnumLiteralDeclaration_1() { return cNominalEnumLiteralDeclaration_1; }
		
		//'Nominal'
		public Keyword getNominalNominalKeyword_1_0() { return cNominalNominalKeyword_1_0; }
		
		//Comparative = 'Comparative'
		public EnumLiteralDeclaration getComparativeEnumLiteralDeclaration_2() { return cComparativeEnumLiteralDeclaration_2; }
		
		//'Comparative'
		public Keyword getComparativeComparativeKeyword_2_0() { return cComparativeComparativeKeyword_2_0; }
	}
	
	private final RelisRootElements pRelisRoot;
	private final StatisticElements pStatistic;
	private final VariableElements pVariable;
	private final EStringElements pEString;
	private final TypeElements eType;
	private final DescriptiveElements pDescriptive;
	private final ComparativeElements pComparative;
	private final EvolutionElements pEvolution;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public RelisTextualGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRelisRoot = new RelisRootElements();
		this.pStatistic = new StatisticElements();
		this.pVariable = new VariableElements();
		this.pEString = new EStringElements();
		this.eType = new TypeElements();
		this.pDescriptive = new DescriptiveElements();
		this.pComparative = new ComparativeElements();
		this.pEvolution = new EvolutionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("geodes.sms.relis.RelisTextual".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RelisRoot returns RelisRoot:
	//    {RelisRoot}
	//    'RelisRoot'
	//    name=EString
	//    '{'
	//        ('variable' '{' variable+=Variable ( "," variable+=Variable)* '}' )?
	//    '}';
	public RelisRootElements getRelisRootAccess() {
		return pRelisRoot;
	}
	
	public ParserRule getRelisRootRule() {
		return getRelisRootAccess().getRule();
	}
	
	//Statistic returns Statistic:
	//    Descriptive | Comparative | Evolution;
	public StatisticElements getStatisticAccess() {
		return pStatistic;
	}
	
	public ParserRule getStatisticRule() {
		return getStatisticAccess().getRule();
	}
	
	//Variable returns Variable:
	//    {Variable}
	//    'Variable'
	//    name=EString
	//    '{'
	//        ('statistic' '{' statistic+=Statistic ( "," statistic+=Statistic)* '}' )?
	//    '}';
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//enum Type returns Type:
	//                Continuous = 'Continuous' | Nominal = 'Nominal' | Comparative = 'Comparative';
	public TypeElements getTypeAccess() {
		return eType;
	}
	
	public EnumRule getTypeRule() {
		return getTypeAccess().getRule();
	}
	
	//Descriptive returns Descriptive:
	//    {Descriptive}
	//    'Descriptive'
	//    name=EString
	//    '{'
	//        ('type' type=Type)?
	//    '}';
	public DescriptiveElements getDescriptiveAccess() {
		return pDescriptive;
	}
	
	public ParserRule getDescriptiveRule() {
		return getDescriptiveAccess().getRule();
	}
	
	//Comparative returns Comparative:
	//    {Comparative}
	//    'Comparative'
	//    name=EString
	//    '{'
	//        ('type' type=Type)?
	//    '}';
	public ComparativeElements getComparativeAccess() {
		return pComparative;
	}
	
	public ParserRule getComparativeRule() {
		return getComparativeAccess().getRule();
	}
	
	//Evolution returns Evolution:
	//    {Evolution}
	//    'Evolution'
	//    name=EString
	//    '{'
	//        ('type' type=Type)?
	//    '}';
	public EvolutionElements getEvolutionAccess() {
		return pEvolution;
	}
	
	public ParserRule getEvolutionRule() {
		return getEvolutionAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
